export enum HTTP_STATUS_CODE {
  HTTP_OK = 200,
  HTTP_CREATED = 201,
  HTTP_NO_CONTENT = 204,
  HTTP_BAD_REQUEST = 400,
  HTTP_UNAUTHORIZED = 401,
  HTTP_FORBIDDEN = 403,
  HTTP_NOT_FOUND = 404,
  HTTP_SESSION_EXPIRED = 419,
  HTTP_UNPROCESSABLE_ENTITY = 422
}

export const DEFAULT_STALE_TIME = 300000

export enum QUERY_KEYS {
  AUTH_ME = 'me',
  AUTH_LOGIN = 'login',
  AUTH_LOGOUT = 'logout'
}
