# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.8'
# Services
services:

    # APP
    app:
        build:
            context: ./.docker
            dockerfile: Dockerfile
        image: markmarilag27/php-nginx:8.1.9
        container_name: app
        restart: unless-stopped
        tty: true
        depends_on:
            - mysql
            - dynamodb
            - sqs
            - mailhog
            - minio
        ports:
            - 80:80
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            - XDEBUG_SESSION=${XDEBUG_SESSION:-0}
            - XDEBUG_CONFIG=${XDEBUG_CONFIG:-client_host=host.docker.internal}
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./.docker/fpm-pool.conf:/etc/php/8.1/fpm/pool.d/www.conf
            - ./.docker/php.ini:/etc/php/8.1/fpm/conf.d/99-php.ini
            - ./.docker/xdebug.ini:/etc/php/8.1/cli/conf.d/20-xdebug.ini
        networks:
            - default
        extra_hosts:
            - host.docker.internal:host-gateway

    # Database
    mysql:
        image: mysql/mysql-server:8.0
        container_name: mysql
        restart: unless-stopped
        ports:
            - ${DB_PORT:-3306}:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: laravel
        volumes:
            - mysql-data:/var/lib/mysql/
        networks:
            - default

    # Dynamodb UI and DB
    dynamodb:
        image: instructure/dynamo-local-admin:latest
        container_name: dynamodb
        restart: unless-stopped
        ports:
            - 8001:8001
            - 8002:8002
        environment:
            DYNAMO_ENDPOINT: ${DYNAMODB_ENDPOINT_LOCAL:-http://localhost:8002}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-laravel}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-password}
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-ap-southeast-1}
            AWS_REGION: ${AWS_DEFAULT_REGION:-ap-southeast-1}
        volumes:
            - dynamodb-data:/var/lib/dynamodb
        networks:
            - default

    # ElasticMQ
    sqs:
        image: softwaremill/elasticmq:latest
        container_name: sqs
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - 9324:9324
            - 9325:9325
        volumes:
            - ./.docker/elasticmq.conf:/opt/elasticmq.conf
            - sqs-data:/data
        networks:
            - default

    # Mail
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        restart: unless-stopped
        ports:
            - ${MAIL_PORT:-1025}:1025
            - 8025:8025
        networks:
            - default

    # Minio Server
    minio:
        image: minio/minio:latest
        container_name: minio
        command: minio server /data --console-address ":9090"
        ports:
            - 9000:9000
            - 9090:9090
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID:-laravel}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY:-password}
        volumes:
            - minio-data:/data
        networks:
            - default

# Networks
networks:
    default:
        driver: bridge

# Volumes
volumes:
    mysql-data:
        driver: local
    minio-data:
        driver: local
    sqs-data:
        driver: local
    dynamodb-data:
        driver: local
